print("System failure imminent!")
print("system reboot has been initiated...")
print()
print("...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting hover engine")
print()
print()
print("System ONLINE")
print()
print("A system reboot has been initiated")
print()
